### ISSUE TITLE
Task to complete for milestone 3

### ISSUE THREAD

**Issue by rasathuraikaran** [cepdnaclk/e18-3yp-Road-Traffic-Ecosystem#19]
- [x] map Streaming
- [x] Make website for admin
- [x] flutter testing
- [x] python testiing 
- [x] UI Completion
- [x] Server hosting
- [x] Twellio call/sms
- [x] clear accidents after one day
- [x] Add description in project website
- [x]  Raspberrypi Inference
- [x] Take gyroscope Reading , and update it to Firebase Data

**Comment by rasathuraikaran** [comment]
all task completed
